channels:
  - conda-forge
dependencies:
  # -------- Core Python --------
  - python=3.13

  # -------- Python Runtime --------
  - numpy
  - pyvista
  - scipy
  - astropy
  - sunpy

  # -------- Build Toolchain --------
  - setuptools
  - python-build

  # -------- Testing / QA --------
  - pytest
  - pytest-cov
  - pytest-benchmark
  - mypy
  - ruff
  - coverage
  - nox

  # -------- Docs --------
  - sphinx
  - sphinx-book-theme
  - sphinx-gallery
  - sphinx-design
  - sphinx-copybutton
  - numpydoc
  - matplotlib
  - python-dotenv
  - imageio-ffmpeg

  # -------- Pip installs --------
  - pip
  - pip:
      - pthree
      - psi-io[hdf4,interp]>=2.2.1
      - mapflpy[hdf4]>=1.2.1
      - psi-data-utils>=1.0.0
      - pyvista[all]